### PR TITLE
use Travis CI to ensure quality

### PR DESCRIPTION
**Pull request by vn971**

### CODE REVIEW

**Comment by vn971** [comment]
It is not building at the moment, needs some improvements, and I'm asking help with. The current problem can be observed here: https://travis-ci.org/vn971/Drawpile/builds/640144263
```
[ 24%] Building CXX object src/libclient/CMakeFiles/dpclient.dir/canvas/selection.cpp.o

/home/travis/build/vn971/Drawpile/src/libclient/canvas/selection.cpp: In member function ‘bool canvas::Selection::closeShape(const QRectF&)’:

/home/travis/build/vn971/Drawpile/src/libclient/canvas/selection.cpp:314:15: error: ‘class QPolygonF’ has no member named ‘intersects’; did you mean ‘intersected’?

   if(!m_shape.intersects(clipRect))

               ^~~~~~~~~~

               intersected

src/libclient/CMakeFiles/dpclient.dir/build.make:319: recipe for target 'src/libclient/CMakeFiles/dpclient.dir/canvas/selection.cpp.o' failed

make[2]: *** [src/libclient/CMakeFiles/dpclient.dir/canvas/selection.cpp.o] Error 1

CMakeFiles/Makefile2:302: recipe for target 'src/libclient/CMakeFiles/dpclient.dir/all' failed

make[1]: *** [src/libclient/CMakeFiles/dpclient.dir/all] Error 2

Makefile:129: recipe for target 'all' failed

make: *** [all] Error 2

The command "cd build && cmake .. && make" exited with 2.
```

**Comment by vn971** [comment]
The failure itself might be related to the relatively recent commit b3385b0bd15aa42ba6f5f5037e49fc8d0e696f55

**Comment by callaa** [comment]
Appears to be so. Looks like the `intersects` function was added in Qt 5.10. That commit also introduced another bug, so I'll fix this at the same time.

**Comment by vn971** [comment]
@callaa nice! Would be cool to see the project compiling on older Qt versions, like the one from latest LTS ubuntu. Unless there's a compelling reason to change at least, but hopefully it's not yet the case.

**Comment by callaa** [comment]
I just pushed a commit that also fixed the use of the too-new API. Does it build now?

**Comment by vn971** [comment]
@callaa nice, thanks! I've merged with `master` now, let's see what CI will say. https://travis-ci.org/vn971/Drawpile/builds

(I'm on FOSDEM now though, so I'm only partly available, if at all.)

**Comment by vn971** [comment]
@callaa awesome! It now successfully builds on ubuntu-18.04 (bionic)!

I wanted to enforce Debian-stretch testing as well (because I know it successfully builds at the moment), but Travis-CI doesn't support it out-of-the-box. I tried to dockerise it, but failed to do so propersly so far: https://travis-ci.org/vn971/Drawpile/branches  So for now, this PR does not do Debian testing - only ubuntu.

To enable Travis-CI for this project, you'll have to include the project on travis-ci.org and then merge this branch into `master`.

Shall we go for that?

**Comment by callaa** [comment]
Looks like it's working. Thank you!

**Pull request merged**
